name: streamdeck_example_plugin
publish_to: 'none'
description: An example plugin for the Elgato Stream Deck built in Dart using package:streamdeck.
version: 0.1.0
repository: https://github.com/DanTup/streamdeck.dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  streamdeck:
    path: ../
  path: ^1.8.2
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.1
